# dockerfile_ imagen base de Docker más reciente
FROM node:latest
# directorio de trabajo dentro del contendor donde copiamos los archicos de la API 
WORKDIR /usr/src/app
# Dependencias de la API
COPY package*.json ./
RUN npm install
# Puerto 300 para la comunicación con Node.js
COPY . .
EXPOSE 3000
CMD [ "npm", "start" ]